meta:
  root_dir: /content/gdrive/MyDrive/Teaching/codes/ocr_27062024/text_detection/src/DB_text_minimal
  round_number: 2
  debug: False
  device: cuda
  test_device: cuda

hps:
  batch_size: 4
  test_batch_size: 1  # must be set to 1 to evaluate metric
  img_size: 640
  no_epochs: 50
  warmup_epochs: 10
  no_classes: 2
  log_iter: 50

lrs:
  mode: poly  # reduce / poly
  warmup_iters: 10
  factor: 0.2
  patience: 8

augmentation:

callbacks:

data:
  icdar2015:
    train_dir: ../data/icdar2015/train_images
    test_dir: ../data/icdar2015/test_images
    train_gt_dir: ../data/icdar2015/train_gts
    test_gt_dir: ../data/icdar2015/test_gts
    ignore_tags: ["###"]
  mix:
    train_dir: /content/gdrive/MyDrive/Teaching/codes/ocr_27062024/data/dbnet_text_data/train
    test_dir: /content/gdrive/MyDrive/Teaching/codes/ocr_27062024/data/dbnet_text_data/val
    train_gt_dir: /content/gdrive/MyDrive/Teaching/codes/ocr_27062024/data/dbnet_text_data/train
    test_gt_dir: /content/gdrive/MyDrive/Teaching/codes/ocr_27062024/data/dbnet_text_data/val
    ignore_tags: ["***"]
dataset:
  name: mix
  return_dict: True

logging:
  logger_file: train.log

loss:

model:
  finetune_cp_path: /content/gdrive/MyDrive/Teaching/codes/ocr_27062024/text_detection/weights/best_pretrained_dbnet.pth
  best_cp_path: /content/gdrive/MyDrive/Teaching/codes/ocr_27062024/text_detection/weights/best_dbnet.pth
  last_cp_path: /content/gdrive/MyDrive/Teaching/codes/ocr_27062024/text_detection/weights/last_dbnet.pth
  best_hmean_cp_path: /content/gdrive/MyDrive/Teaching/codes/ocr_27062024/text_detection/weights/best_f1_dbnet.pth

optimizer:
  type: adam
  lr: 0.005
  lr_finetune: 0.001
  weight_decay: 0
  reduction: mean
  alpha: 1
  beta: 10
  negative_ratio: 3
  amsgrad: False

metric:
  thred_text_score: 0.25
  prob_threshold: 0.5
  unclip_ratio: 1.50
  is_output_polygon: True

private:

scheduler:

trainer:

training: